
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Tue Dec 12 15:00:12 GMT+02:00 2006
//----------------------------------------------------

package slp;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LT = 11;
  public static final int PLUS = 2;
  public static final int RPAREN = 7;
  public static final int LOR = 15;
  public static final int SEMI = 8;
  public static final int LPAREN = 6;
  public static final int GT = 10;
  public static final int LAND = 14;
  public static final int LE = 13;
  public static final int READI = 16;
  public static final int NUMBER = 18;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int DIV = 5;
  public static final int GE = 12;
  public static final int MINUS = 3;
  public static final int PRINT = 17;
  public static final int error = 1;
  public static final int ASSIGN = 9;
  public static final int VAR = 19;
  public static final int UMINUS = 20;
}

