
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 06 16:00:45 IST 2016
//----------------------------------------------------

package slp.mcode;

/** CUP generated interface containing symbol constants. */
public interface McodeSym {
  /* terminals */
  public static final int XOR_VAR_REG = 52;
  public static final int MOVEARRAY_IMM_REG__IMM = 21;
  public static final int COMPARE_REG_REG = 56;
  public static final int MOVEARRAY_IMM_REG__REG = 20;
  public static final int SUB_REG_REG = 35;
  public static final int MUL_IMM_REG = 36;
  public static final int MOD_VAR_REG = 43;
  public static final int MOVE_IMM_VAR = 13;
  public static final int JUMPGE = 65;
  public static final int XOR_IMM_REG = 51;
  public static final int COMMA = 7;
  public static final int AND_REG_REG = 47;
  public static final int MOD_IMM_REG = 42;
  public static final int MOVE = 86;
  public static final int OR_VAR_REG = 49;
  public static final int LP = 2;
  public static final int SUB = 77;
  public static final int DIV_REG_REG = 41;
  public static final int RP = 3;
  public static final int COMPARE = 84;
  public static final int MOVEFIELD = 89;
  public static final int NOT = 60;
  public static final int JUMPLE = 67;
  public static final int DEC = 58;
  public static final int VAR = 73;
  public static final int LB = 4;
  public static final int OR_IMM_REG = 48;
  public static final int STATICCALL = 69;
  public static final int MOVE_REG_VAR = 11;
  public static final int RB = 5;
  public static final int XOR_REG_REG = 53;
  public static final int JUMP = 61;
  public static final int MUL = 78;
  public static final int MOD = 80;
  public static final int MOVEFIELD_REG___IMM_REG = 23;
  public static final int JUMPFALSE = 63;
  public static final int MOVE_VAR_REG = 12;
  public static final int NUMBER = 72;
  public static final int MOVEFIELD_IMM_REG___IMM = 27;
  public static final int MOD_REG_REG = 44;
  public static final int MUL_REG_REG = 38;
  public static final int JUMPL = 66;
  public static final int MOVEFIELD_IMM_REG___REG = 26;
  public static final int JUMPG = 64;
  public static final int ASSIGN = 9;
  public static final int ARRAYLENGTH_VAR_REG = 28;
  public static final int ADD_VAR_REG = 31;
  public static final int DIV = 79;
  public static final int ADD = 76;
  public static final int RETURN = 71;
  public static final int MOVEARRAY_REG__IMM_REG = 17;
  public static final int COMPARE_VAR_REG = 55;
  public static final int ARRAYLENGTH = 88;
  public static final int DOT = 6;
  public static final int MOVEFIELD_REG___REG_REG = 22;
  public static final int MOVE_IMM_REG = 15;
  public static final int EOF = 0;
  public static final int ADD_IMM_REG = 30;
  public static final int OR_REG_REG = 50;
  public static final int INC = 57;
  public static final int COMPARE_IMM_REG = 54;
  public static final int LABEL = 75;
  public static final int SUB_VAR_REG = 34;
  public static final int LIBRARY = 70;
  public static final int MOVEARRAY = 87;
  public static final int OR = 82;
  public static final int VIRTUALLCALL = 68;
  public static final int error = 1;
  public static final int JUMPTRUE = 62;
  public static final int DIV_VAR_REG = 40;
  public static final int MOVEARRAY_REG__REG_REG = 16;
  public static final int MOVEARRAY_REG_REG__IMM = 19;
  public static final int COLON = 8;
  public static final int MOVE_REG_IMM = 14;
  public static final int SUB_IMM_REG = 33;
  public static final int REG = 74;
  public static final int AND_VAR_REG = 46;
  public static final int MOVEARRAY_REG_REG__REG = 18;
  public static final int MOVE_REG_REG = 10;
  public static final int ADD_REG_REG = 32;
  public static final int STRING = 85;
  public static final int DIV_IMM_REG = 39;
  public static final int MOVEFIELD_REG_REG___IMM = 25;
  public static final int AND = 81;
  public static final int AND_IMM_REG = 45;
  public static final int MOVEFIELD_REG_REG___REG = 24;
  public static final int ARRAYLENGTH_REG_REG = 29;
  public static final int NEG = 59;
  public static final int XOR = 83;
  public static final int MUL_VAR_REG = 37;
}

