
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 03 21:22:13 IST 2016
//----------------------------------------------------

package slp.mcode;

/** CUP generated interface containing symbol constants. */
public interface McodeSym {
  /* terminals */
  public static final int MOVEARRAY = 11;
  public static final int STATICCALL = 35;
  public static final int MOVEFIELD = 13;
  public static final int XOR = 25;
  public static final int REG = 40;
  public static final int LIBRARY = 36;
  public static final int NOT = 22;
  public static final int AND = 23;
  public static final int LP = 2;
  public static final int OR = 24;
  public static final int COMMA = 7;
  public static final int JUMPTRUE = 28;
  public static final int JUMPGE = 31;
  public static final int INC = 19;
  public static final int DIV = 17;
  public static final int RP = 3;
  public static final int ASSIGN = 9;
  public static final int DOT = 6;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int LB = 4;
  public static final int error = 1;
  public static final int MUL = 16;
  public static final int RB = 5;
  public static final int JUMPFALSE = 29;
  public static final int ADD = 14;
  public static final int JUMP = 27;
  public static final int NUMBER = 38;
  public static final int MOD = 18;
  public static final int ARRAYLENGTH = 12;
  public static final int VIRTUALLCALL = 34;
  public static final int MOVE = 10;
  public static final int COMPARE = 26;
  public static final int COLON = 8;
  public static final int NEG = 21;
  public static final int JUMPLE = 33;
  public static final int JUMPL = 32;
  public static final int STRING = 42;
  public static final int JUMPG = 30;
  public static final int DEC = 20;
  public static final int LABEL = 41;
  public static final int SUB = 15;
  public static final int VAR = 39;
}

