
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 20 13:21:03 IST 2015
//----------------------------------------------------

package slp;

/** CUP generated interface containing symbol constants. */
public interface Slp_badSym {
  /* terminals */
  public static final int LT = 11;
  public static final int PLUS = 6;
  public static final int RPAREN = 3;
  public static final int LOR = 15;
  public static final int SEMI = 4;
  public static final int LPAREN = 2;
  public static final int GT = 10;
  public static final int LAND = 14;
  public static final int LE = 13;
  public static final int READI = 16;
  public static final int NUMBER = 18;
  public static final int EOF = 0;
  public static final int MULT = 8;
  public static final int DIV = 9;
  public static final int GE = 12;
  public static final int MINUS = 7;
  public static final int PRINT = 17;
  public static final int error = 1;
  public static final int ASSIGN = 5;
  public static final int VAR = 19;
  public static final int UMINUS = 20;
}

