
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 20 13:56:59 IST 2015
//----------------------------------------------------

package slp;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LCBR = 28;
  public static final int MULT = 8;
  public static final int GE = 22;
  public static final int UMINUS = 6;
  public static final int SEMI = 43;
  public static final int LPAREN = 27;
  public static final int CONTINUE = 15;
  public static final int INT = 24;
  public static final int MINUS = 35;
  public static final int STATIC = 44;
  public static final int RPAREN = 42;
  public static final int LT = 33;
  public static final int COMMA = 14;
  public static final int CLASS = 13;
  public static final int DIV = 9;
  public static final int READI = 2;
  public static final int PLUS = 7;
  public static final int QUOTE = 46;
  public static final int ASSIGN = 10;
  public static final int IF = 23;
  public static final int THIS = 47;
  public static final int DOT = 16;
  public static final int LE = 34;
  public static final int EOF = 0;
  public static final int BOOLEAN = 11;
  public static final int RETURN = 41;
  public static final int RCBR = 40;
  public static final int LB = 26;
  public static final int LAND = 25;
  public static final int EQUAL = 17;
  public static final int TRUE = 48;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int RB = 39;
  public static final int LOR = 32;
  public static final int NULL = 38;
  public static final int MOD = 36;
  public static final int NUMBER = 4;
  public static final int BREAK = 12;
  public static final int VOID = 49;
  public static final int ELSE = 19;
  public static final int WHILE = 50;
  public static final int NEQUAL = 37;
  public static final int EXTENDS = 18;
  public static final int STRING = 45;
  public static final int LNEG = 31;
  public static final int FALSE = 20;
  public static final int GT = 21;
  public static final int VAR = 5;
  public static final int PRINT = 3;
  public static final int LENGTH = 29;
}

