
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 03 19:38:47 IST 2015
//----------------------------------------------------

package slp;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LCBR = 24;
  public static final int MULT = 46;
  public static final int GE = 48;
  public static final int UMINUS = 5;
  public static final int SEMI = 38;
  public static final int LPAREN = 23;
  public static final int CONTINUE = 12;
  public static final int INT = 20;
  public static final int MINUS = 30;
  public static final int STATIC = 39;
  public static final int RPAREN = 37;
  public static final int LT = 29;
  public static final int COMMA = 11;
  public static final int CLASS = 10;
  public static final int DIV = 47;
  public static final int PLUS = 6;
  public static final int QUOTE = 41;
  public static final int ASSIGN = 7;
  public static final int IF = 19;
  public static final int THIS = 42;
  public static final int DOT = 13;
  public static final int LE = 49;
  public static final int EOF = 0;
  public static final int BOOLEAN = 8;
  public static final int RETURN = 36;
  public static final int RCBR = 35;
  public static final int LB = 22;
  public static final int LAND = 21;
  public static final int EQUAL = 14;
  public static final int TRUE = 43;
  public static final int NEW = 26;
  public static final int error = 1;
  public static final int RB = 34;
  public static final int LOR = 28;
  public static final int NULL = 33;
  public static final int NUMBER = 2;
  public static final int MOD = 31;
  public static final int BREAK = 9;
  public static final int VOID = 44;
  public static final int ELSE = 16;
  public static final int WHILE = 45;
  public static final int NEQUAL = 32;
  public static final int CLASS_ID = 4;
  public static final int EXTENDS = 15;
  public static final int STRING = 40;
  public static final int LNEG = 27;
  public static final int FALSE = 17;
  public static final int GT = 18;
  public static final int VAR = 3;
  public static final int LENGTH = 25;
}

