/* The following code was generated by JFlex 1.4.3 on 18:56 07/11/15 */

/***************************/
/* FILE NAME: LEX_FILE.lex */
/***************************/

/***************************/
/* AUTHOR: OREN ISH SHALOM */
/***************************/
/**/
/*************/
/* USER CODE */
/*************/
   
import java_cup.runtime.*;

/******************************/
/* DOLAR DOLAR - DON'T TOUCH! */
/******************************/
      

class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\13\1\52\1\7"+
    "\2\0\1\56\1\43\1\12\1\45\1\61\1\15\1\16\1\32\1\55"+
    "\1\36\1\14\1\4\11\5\1\0\1\62\1\54\1\17\1\42\1\12"+
    "\1\0\32\11\1\44\1\10\1\57\1\0\1\6\1\0\1\24\1\20"+
    "\1\30\1\40\1\23\1\41\1\47\1\50\1\34\1\6\1\27\1\22"+
    "\1\6\1\25\1\21\2\6\1\26\1\31\1\33\1\35\1\63\1\51"+
    "\1\37\2\6\1\46\1\53\1\60\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\2\2\1\3\1\0\1\4\1\5\1\6"+
    "\1\7\1\10\7\3\1\11\2\3\1\12\1\3\1\13"+
    "\1\0\1\14\1\15\1\16\1\3\1\17\1\0\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\3\1\27"+
    "\3\0\1\30\16\3\1\31\1\3\1\32\1\33\1\3"+
    "\1\34\1\35\1\36\1\3\1\0\5\3\1\37\10\3"+
    "\1\40\6\3\1\41\1\3\1\42\5\3\1\43\1\44"+
    "\2\3\1\45\1\3\1\46\4\3\1\47\2\3\1\50"+
    "\1\51\1\3\1\52\1\3\1\53\1\3\1\54\1\55"+
    "\1\56\1\57\1\3\1\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\150\0\234\0\320\0\u0104\0\u0138"+
    "\0\u016c\0\150\0\150\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270"+
    "\0\u02a4\0\u02d8\0\u030c\0\150\0\u0340\0\u0374\0\150\0\u03a8"+
    "\0\u03dc\0\u0410\0\150\0\150\0\150\0\u0444\0\u0478\0\u04ac"+
    "\0\u04e0\0\150\0\150\0\150\0\150\0\150\0\150\0\u0514"+
    "\0\150\0\u0548\0\u057c\0\u05b0\0\150\0\u05e4\0\u0618\0\u064c"+
    "\0\u0680\0\u06b4\0\u06e8\0\u071c\0\u0750\0\u0784\0\u07b8\0\u07ec"+
    "\0\u0820\0\u0854\0\u0888\0\320\0\u08bc\0\150\0\150\0\u08f0"+
    "\0\150\0\150\0\150\0\u0924\0\u0958\0\u098c\0\u09c0\0\u09f4"+
    "\0\u0a28\0\u0a5c\0\320\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\u0b60"+
    "\0\u0b94\0\u0bc8\0\u0bfc\0\320\0\u0c30\0\u0c64\0\u0c98\0\u0ccc"+
    "\0\u0d00\0\u0d34\0\320\0\u0d68\0\320\0\u0d9c\0\u0dd0\0\u0e04"+
    "\0\u0e38\0\u0e6c\0\320\0\320\0\u0ea0\0\u0ed4\0\320\0\u0f08"+
    "\0\320\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8\0\320\0\u100c\0\u1040"+
    "\0\320\0\320\0\u1074\0\320\0\u10a8\0\320\0\u10dc\0\320"+
    "\0\320\0\320\0\320\0\u1110\0\320";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\2\3\1\4\1\5\1\6\1\7\1\0"+
    "\1\10\1\0\1\3\1\11\1\12\1\13\1\14\1\15"+
    "\1\6\1\16\1\17\1\6\1\20\1\21\1\6\1\22"+
    "\1\23\1\24\1\25\1\26\1\6\1\27\2\6\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\2\6\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\2\0\1\3\151\0\2\5\62\0\3\6\2\0"+
    "\1\6\6\0\12\6\1\0\3\6\1\0\3\6\5\0"+
    "\3\6\11\0\1\6\7\7\1\51\1\52\53\7\4\0"+
    "\3\10\2\0\1\10\6\0\12\10\1\0\3\10\1\0"+
    "\3\10\5\0\3\10\11\0\1\10\14\0\1\53\1\54"+
    "\65\0\1\55\50\0\3\6\2\0\1\6\6\0\1\6"+
    "\1\56\4\6\1\57\3\6\1\0\3\6\1\0\3\6"+
    "\5\0\3\6\11\0\1\6\4\0\3\6\2\0\1\6"+
    "\6\0\3\6\1\60\6\6\1\0\3\6\1\0\3\6"+
    "\5\0\3\6\11\0\1\6\4\0\3\6\2\0\1\6"+
    "\6\0\2\6\1\61\7\6\1\0\3\6\1\0\1\62"+
    "\2\6\5\0\3\6\11\0\1\6\4\0\3\6\2\0"+
    "\1\6\6\0\3\6\1\63\6\6\1\0\2\6\1\64"+
    "\1\0\3\6\5\0\3\6\11\0\1\6\4\0\3\6"+
    "\2\0\1\6\6\0\3\6\1\65\6\6\1\0\3\6"+
    "\1\0\3\6\5\0\3\6\11\0\1\6\4\0\3\6"+
    "\2\0\1\6\6\0\1\6\1\66\1\67\7\6\1\0"+
    "\3\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\12\6\1\0\1\70\2\6"+
    "\1\0\3\6\5\0\3\6\11\0\1\6\4\0\3\6"+
    "\2\0\1\6\6\0\6\6\1\71\3\6\1\0\3\6"+
    "\1\0\3\6\5\0\1\6\1\72\1\6\11\0\1\6"+
    "\4\0\3\6\2\0\1\6\6\0\5\6\1\73\4\6"+
    "\1\0\3\6\1\0\2\6\1\74\5\0\3\6\11\0"+
    "\1\6\4\0\3\6\2\0\1\6\6\0\4\6\1\75"+
    "\5\6\1\0\3\6\1\0\3\6\5\0\3\6\11\0"+
    "\1\6\17\0\1\76\107\0\1\77\24\0\3\6\2\0"+
    "\1\6\6\0\12\6\1\0\3\6\1\0\3\6\5\0"+
    "\1\6\1\100\1\6\11\0\1\6\17\0\1\101\117\0"+
    "\1\102\27\0\1\103\50\0\3\6\2\0\1\6\6\0"+
    "\1\6\1\104\10\6\1\0\3\6\1\0\3\6\5\0"+
    "\3\6\11\0\1\6\7\0\2\7\54\0\1\2\1\3"+
    "\1\0\4\53\1\0\3\53\4\0\12\53\1\0\7\53"+
    "\5\0\4\53\7\0\2\53\4\0\4\54\1\0\3\54"+
    "\1\0\1\105\2\0\12\54\1\0\7\54\5\0\4\54"+
    "\7\0\2\54\4\0\3\6\2\0\1\6\6\0\1\6"+
    "\1\106\10\6\1\0\3\6\1\0\3\6\5\0\3\6"+
    "\11\0\1\6\4\0\3\6\2\0\1\6\6\0\3\6"+
    "\1\107\6\6\1\0\3\6\1\0\3\6\5\0\3\6"+
    "\11\0\1\6\4\0\3\6\2\0\1\6\6\0\5\6"+
    "\1\110\4\6\1\0\3\6\1\0\3\6\5\0\3\6"+
    "\11\0\1\6\4\0\3\6\2\0\1\6\6\0\11\6"+
    "\1\111\1\0\3\6\1\0\3\6\5\0\3\6\11\0"+
    "\1\6\4\0\3\6\2\0\1\6\6\0\12\6\1\0"+
    "\1\112\2\6\1\0\3\6\5\0\3\6\11\0\1\6"+
    "\4\0\3\6\2\0\1\6\6\0\12\6\1\0\3\6"+
    "\1\0\3\6\5\0\2\6\1\113\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\2\6\1\114\7\6\1\0"+
    "\3\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\12\6\1\0\1\115\2\6"+
    "\1\0\3\6\5\0\3\6\11\0\1\6\4\0\3\6"+
    "\2\0\1\6\6\0\5\6\1\116\4\6\1\0\3\6"+
    "\1\0\3\6\5\0\3\6\11\0\1\6\4\0\3\6"+
    "\2\0\1\6\6\0\4\6\1\117\5\6\1\0\3\6"+
    "\1\0\3\6\5\0\3\6\11\0\1\6\4\0\3\6"+
    "\2\0\1\6\6\0\4\6\1\120\1\6\1\121\3\6"+
    "\1\0\3\6\1\0\3\6\5\0\3\6\11\0\1\6"+
    "\4\0\3\6\2\0\1\6\6\0\12\6\1\0\2\6"+
    "\1\122\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\12\6\1\0\1\6\1\123"+
    "\1\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\12\6\1\0\1\124\2\6"+
    "\1\0\3\6\5\0\3\6\11\0\1\6\4\0\3\6"+
    "\2\0\1\6\6\0\2\6\1\125\7\6\1\0\3\6"+
    "\1\0\3\6\5\0\3\6\11\0\1\6\4\0\3\6"+
    "\2\0\1\6\6\0\12\6\1\0\1\6\1\126\1\6"+
    "\1\0\3\6\5\0\3\6\11\0\1\6\4\0\3\6"+
    "\2\0\1\6\6\0\12\6\1\0\1\6\1\127\1\6"+
    "\1\0\3\6\5\0\3\6\11\0\1\6\14\0\1\3"+
    "\53\0\3\6\2\0\1\6\6\0\2\6\1\130\7\6"+
    "\1\0\3\6\1\0\3\6\5\0\3\6\11\0\1\6"+
    "\4\0\3\6\2\0\1\6\6\0\4\6\1\131\5\6"+
    "\1\0\3\6\1\0\3\6\5\0\3\6\11\0\1\6"+
    "\4\0\3\6\2\0\1\6\6\0\12\6\1\0\3\6"+
    "\1\0\3\6\5\0\1\132\2\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\3\6\1\133\6\6\1\0"+
    "\3\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\3\6\1\134\6\6\1\0"+
    "\3\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\2\6\1\135\7\6\1\0"+
    "\3\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\12\6\1\0\2\6\1\136"+
    "\1\0\3\6\5\0\3\6\11\0\1\6\4\0\3\6"+
    "\2\0\1\6\6\0\12\6\1\0\1\137\2\6\1\0"+
    "\3\6\5\0\3\6\11\0\1\6\4\0\3\6\2\0"+
    "\1\6\6\0\11\6\1\140\1\0\3\6\1\0\3\6"+
    "\5\0\3\6\11\0\1\6\4\0\3\6\2\0\1\6"+
    "\6\0\12\6\1\0\1\141\2\6\1\0\3\6\5\0"+
    "\3\6\11\0\1\6\4\0\3\6\2\0\1\6\6\0"+
    "\12\6\1\0\1\6\1\142\1\6\1\0\3\6\5\0"+
    "\3\6\11\0\1\6\4\0\3\6\2\0\1\6\6\0"+
    "\3\6\1\143\6\6\1\0\3\6\1\0\3\6\5\0"+
    "\3\6\11\0\1\6\4\0\3\6\2\0\1\6\6\0"+
    "\11\6\1\144\1\0\3\6\1\0\3\6\5\0\3\6"+
    "\11\0\1\6\4\0\3\6\2\0\1\6\6\0\11\6"+
    "\1\145\1\0\3\6\1\0\3\6\5\0\3\6\11\0"+
    "\1\6\4\0\3\6\2\0\1\6\6\0\2\6\1\146"+
    "\7\6\1\0\3\6\1\0\3\6\5\0\3\6\11\0"+
    "\1\6\4\0\3\6\2\0\1\6\6\0\12\6\1\0"+
    "\3\6\1\0\1\6\1\147\1\6\5\0\3\6\11\0"+
    "\1\6\4\0\3\6\2\0\1\6\6\0\3\6\1\150"+
    "\6\6\1\0\3\6\1\0\3\6\5\0\3\6\11\0"+
    "\1\6\4\0\3\6\2\0\1\6\6\0\7\6\1\151"+
    "\2\6\1\0\3\6\1\0\3\6\5\0\3\6\11\0"+
    "\1\6\4\0\3\6\2\0\1\6\6\0\12\6\1\0"+
    "\1\152\2\6\1\0\3\6\5\0\3\6\11\0\1\6"+
    "\4\0\3\6\2\0\1\6\6\0\5\6\1\153\4\6"+
    "\1\0\3\6\1\0\3\6\5\0\3\6\11\0\1\6"+
    "\4\0\3\6\2\0\1\6\6\0\6\6\1\154\3\6"+
    "\1\0\3\6\1\0\3\6\5\0\3\6\11\0\1\6"+
    "\4\0\3\6\2\0\1\6\6\0\12\6\1\0\1\6"+
    "\1\155\1\6\1\0\3\6\5\0\3\6\11\0\1\6"+
    "\4\0\3\6\2\0\1\6\6\0\11\6\1\156\1\0"+
    "\3\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\12\6\1\0\1\6\1\157"+
    "\1\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\5\6\1\160\4\6\1\0"+
    "\3\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\3\6\1\161\6\6\1\0"+
    "\3\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\3\6\1\162\6\6\1\0"+
    "\3\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\4\6\1\163\5\6\1\0"+
    "\3\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\12\6\1\0\3\6\1\0"+
    "\3\6\5\0\1\6\1\164\1\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\12\6\1\0\3\6\1\0"+
    "\1\6\1\165\1\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\5\6\1\166\4\6\1\0"+
    "\3\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\5\6\1\167\4\6\1\0"+
    "\3\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\10\6\1\170\1\6\1\0"+
    "\3\6\1\0\3\6\5\0\3\6\11\0\1\6\4\0"+
    "\3\6\2\0\1\6\6\0\12\6\1\0\3\6\1\0"+
    "\3\6\5\0\1\171\2\6\11\0\1\6\4\0\3\6"+
    "\2\0\1\6\6\0\5\6\1\172\4\6\1\0\3\6"+
    "\1\0\3\6\5\0\3\6\11\0\1\6\4\0\3\6"+
    "\2\0\1\6\6\0\11\6\1\173\1\0\3\6\1\0"+
    "\3\6\5\0\3\6\11\0\1\6\4\0\3\6\2\0"+
    "\1\6\6\0\12\6\1\0\2\6\1\174\1\0\3\6"+
    "\5\0\3\6\11\0\1\6\4\0\3\6\2\0\1\6"+
    "\6\0\3\6\1\175\6\6\1\0\3\6\1\0\3\6"+
    "\5\0\3\6\11\0\1\6";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4420];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\2\11\2\1\1\0\2\1\2\11\10\1"+
    "\1\11\2\1\1\11\2\1\1\0\3\11\2\1\1\0"+
    "\1\1\6\11\1\1\1\11\3\0\1\11\20\1\2\11"+
    "\1\1\3\11\1\1\1\0\70\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    /*********************************************************************************/
    /* Create a new java_cup.runtime.Symbol with information about the current token */
    /*********************************************************************************/
    private Symbol symbol(int type)               {return new Symbol(type, yyline, yycolumn);}
    private Symbol symbol(int type, Object value) {return new Symbol(type, yyline, yycolumn, value);}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 36: 
          { System.out.println(yyline +": THIS");	return symbol(sym.THIS);
          }
        case 49: break;
        case 7: 
          { System.out.println(yyline+": PLUS");     return symbol(sym.PLUS);
          }
        case 50: break;
        case 28: 
          { System.out.println(yyline +": NEQUAL");    return symbol(sym.NEQUAL);
          }
        case 51: break;
        case 42: 
          { System.out.println(yyline+": LENGTH");    return symbol(sym.LENGTH);
          }
        case 52: break;
        case 14: 
          { System.out.println(yyline+": LBCR");    return symbol(sym.LCBR);
          }
        case 53: break;
        case 12: 
          { System.out.println(yyline+": LB");    return symbol(sym.LB);
          }
        case 54: break;
        case 38: 
          { System.out.println(yyline+ ": BREAK");    return symbol(sym.BREAK);
          }
        case 55: break;
        case 11: 
          { System.out.println(yyline+": GT");    return symbol(sym.GT);
          }
        case 56: break;
        case 46: 
          { System.out.println(yyline+": BOOLEAN");    return symbol(sym.BOOLEAN);
          }
        case 57: break;
        case 8: 
          { System.out.println(yyline+": ASSIGN");    return symbol(sym.ASSIGN);
          }
        case 58: break;
        case 1: 
          { /* just skip what was found, do nothing */
          }
        case 59: break;
        case 22: 
          { System.out.println(yyline+": SEMI");    return symbol(sym.SEMI);
          }
        case 60: break;
        case 3: 
          { System.out.print(yyline +": ID(");
						System.out.print(yytext());
						System.out.println(") ");
						return symbol(sym.ID, new String(yytext()));
          }
        case 61: break;
        case 19: 
          { System.out.println(yyline + ": RB");    return symbol(sym.RB);
          }
        case 62: break;
        case 32: 
          { System.out.println(yyline+": INT");    return symbol(sym.INT);
          }
        case 63: break;
        case 10: 
          { System.out.println(yyline +": DOT");    return symbol(sym.DOT);
          }
        case 64: break;
        case 18: 
          { System.out.println(yyline+": MOD");    return symbol(sym.MOD);
          }
        case 65: break;
        case 45: 
          { System.out.println(yyline +": STRING");	return symbol(sym.STRING);
          }
        case 66: break;
        case 29: 
          { System.out.println(yyline+": LOR");    return symbol(sym.LOR);
          }
        case 67: break;
        case 39: 
          { System.out.println(yyline+ ": CLASS");    return symbol(sym.CLASS);
          }
        case 68: break;
        case 20: 
          { System.out.println(yyline +": RCBR");    return symbol(sym.RCBR);
          }
        case 69: break;
        case 40: 
          { System.out.println(yyline+ ": FALSE");    return symbol(sym.FALSE);
          }
        case 70: break;
        case 33: 
          { System.out.println(yyline +": ELSE");    return symbol(sym.ELSE);
          }
        case 71: break;
        case 41: 
          { System.out.println(yyline +": WHILE"); return symbol(sym.WHILE);
          }
        case 72: break;
        case 15: 
          { System.out.println(yyline+": LNEG");    return symbol(sym.LNEG);
          }
        case 73: break;
        case 26: 
          { System.out.println(yyline+": GTE");    return symbol(sym.GTE);
          }
        case 74: break;
        case 30: 
          { System.out.println(yyline+": LTE");    return symbol(sym.LTE);
          }
        case 75: break;
        case 31: 
          { System.out.println(yyline+": NEW");    return symbol(sym.NEW);
          }
        case 76: break;
        case 17: 
          { System.out.println(yyline+": MINUS");    return symbol(sym.MINUS);
          }
        case 77: break;
        case 47: 
          { System.out.println(yyline+ ": EXTENDS");    return symbol(sym.EXTENDS);
          }
        case 78: break;
        case 13: 
          { System.out.println(yyline+": LP");    return symbol(sym.LP);
          }
        case 79: break;
        case 21: 
          { System.out.println(yyline+": RP");    return symbol(sym.RP);
          }
        case 80: break;
        case 27: 
          { System.out.println(yyline+": LAND");    return symbol(sym.LAND);
          }
        case 81: break;
        case 24: 
          { System.out.println(yyline +": EQUAL");    return symbol(sym.EQUAL);
          }
        case 82: break;
        case 25: 
          { System.out.println(yyline +": IF");    return symbol(sym.IF);
          }
        case 83: break;
        case 16: 
          { System.out.println(yyline+": LT");    return symbol(sym.LT);
          }
        case 84: break;
        case 48: 
          { System.out.println(yyline +": CONTINUE");    return symbol(sym.CONTINUE);
          }
        case 85: break;
        case 34: 
          { System.out.println(yyline +": NULL");    return symbol(sym.NULL);
          }
        case 86: break;
        case 43: 
          { System.out.println(yyline+": RETURN");    return symbol(sym.RETURN);
          }
        case 87: break;
        case 35: 
          { System.out.println(yyline +": TRUE");	return symbol(sym.TRUE);
          }
        case 88: break;
        case 23: 
          { System.out.print("QUOTE(");
						System.out.print(yytext());
						System.out.print(") ");
						return symbol(sym.QUOTE, new String(yytext()));
          }
        case 89: break;
        case 44: 
          { System.out.println(yyline +": STATIC");	return symbol(sym.STATIC);
          }
        case 90: break;
        case 4: 
          { System.out.print(yyline+": CLASS_ID(");
						System.out.print(yytext());
						System.out.println(") ");
						return symbol(sym.CLASS_ID, new String(yytext()));
          }
        case 91: break;
        case 9: 
          { System.out.println(yyline+": COMMA");    return symbol(sym.COMMA);
          }
        case 92: break;
        case 6: 
          { System.out.println(yyline+": MULTIPLY");    return symbol(sym.MULTIPLY);
          }
        case 93: break;
        case 2: 
          { System.out.print(yyline +": INTEGER(");
						System.out.print(yytext());
						System.out.println(") ");
						return symbol(sym.NUMBER, new Integer(yytext()));
          }
        case 94: break;
        case 37: 
          { System.out.println(yyline +": VOID");	return symbol(sym.VOID);
          }
        case 95: break;
        case 5: 
          { System.out.println(yyline +": DIVIDE ");    return symbol(sym.DIVIDE);
          }
        case 96: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case YYINITIAL: {
              System.out.print(yyline +": EOF");	System.exit(0);
            }
            case 126: break;
            default:
              { return new java_cup.runtime.Symbol(sym.EOF); }
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
