
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 04 00:35:56 IST 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 4;
  public static final int CONTINUE = 13;
  public static final int ELSE = 17;
  public static final int CLASS = 11;
  public static final int SEMICOLON = 2;
  public static final int PLUS = 3;
  public static final int RPAREN = 7;
  public static final int EQUAL = 15;
  public static final int GT = 19;
  public static final int LPAREN = 6;
  public static final int ID = 22;
  public static final int GTE = 20;
  public static final int BOOLEAN = 9;
  public static final int COMMA = 12;
  public static final int NUMBER = 21;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int BREAK = 10;
  public static final int FALSE = 18;
  public static final int error = 1;
  public static final int DOT = 14;
  public static final int ASSIGN = 8;
  public static final int CLASS_ID = 23;
  public static final int EXTENDS = 16;
}

