
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 08 16:04:56 IST 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 4;
  public static final int LCBR = 23;
  public static final int LTE = 29;
  public static final int SEMI = 38;
  public static final int CONTINUE = 10;
  public static final int INT = 19;
  public static final int MINUS = 30;
  public static final int STATIC = 39;
  public static final int LT = 28;
  public static final int LP = 22;
  public static final int COMMA = 9;
  public static final int CLASS = 8;
  public static final int RP = 37;
  public static final int PLUS = 2;
  public static final int MULTIPLY = 3;
  public static final int QUOTE = 41;
  public static final int ASSIGN = 5;
  public static final int IF = 18;
  public static final int THIS = 42;
  public static final int ID = 47;
  public static final int DOT = 11;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int RETURN = 36;
  public static final int RCBR = 35;
  public static final int LB = 21;
  public static final int LAND = 20;
  public static final int EQUAL = 12;
  public static final int TRUE = 43;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int RB = 34;
  public static final int LOR = 27;
  public static final int NULL = 33;
  public static final int NUMBER = 46;
  public static final int MOD = 31;
  public static final int BREAK = 7;
  public static final int VOID = 44;
  public static final int GTE = 17;
  public static final int ELSE = 14;
  public static final int WHILE = 45;
  public static final int NEQUAL = 32;
  public static final int CLASS_ID = 48;
  public static final int EXTENDS = 13;
  public static final int STRING = 40;
  public static final int LNEG = 26;
  public static final int FALSE = 15;
  public static final int GT = 16;
  public static final int LENGTH = 24;
}

