
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 04 00:35:55 IST 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface YcalcSym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int DIVIDE = 6;
  public static final int NUMBER = 9;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int ID = 10;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int TIMES = 5;
  public static final int LPAREN = 7;
}

